In [1]:
import datetime
import platform

import pandas as pd
import json
from urllib.request import urlopen

In [2]:
def usa_counties():
    """[summary]: Returns live cases of USA at county-level
    
    source:
        ³ nytimes
    Returns:
        [pd.DataFrame]
    """
    populations = pd.read_csv('https://raw.githubusercontent.com/balsama/us_counties_data/master/data/counties.csv')[['FIPS Code', 'Population']]
    populations.rename(columns={'FIPS Code': 'fips'}, inplace=True)
    df = pd.read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-counties.csv', dtype={"fips": str}).iloc[:,:6]
    df = pd.merge(df, populations, on='fips')
    df['cases/capita'] = (df.cases / df.Population)*100000 # per 100k residents

    return df
usa_counties()

,date,county,state,fips,cases,deaths,Population,cases/capita
0,2021-04-26,Autauga,Alabama,01001,6879,107.0,54571,12605.596379
1,2021-04-26,Baldwin,Alabama,01003,20847,305.0,182265,11437.741750
2,2021-04-26,Barbour,Alabama,01005,2296,56.0,27457,8362.166296
3,2021-04-26,Bibb,Alabama,01007,2584,62.0,22915,11276.456470
4,2021-04-26,Blount,Alabama,01009,6571,134.0,57322,11463.312515
...,...,...,...,...,...,...,...,...
3080,2021-04-26,Sweetwater,Wyoming,56037,4159,37.0,45267,9187.708485
3081,2021-04-26,Teton,Wyoming,56039,3719,9.0,21675,17158.016148
3082,2021-04-26,Uinta,Wyoming,56041,2158,12.0,21025,10263.971463
3083,2021-04-26,Washakie,Wyoming,56043,897,26.0,8464,10597.826087
3084,2021-04-26,Weston,Wyoming,56045,648,5.0,7082,9149.957639